### ISSUE TITLE
Homogeneous test framework over the project

### ISSUE THREAD

**Issue by ydarias** [Qiskit/qiskit-vscode#14]
### What is the expected enhancement?

The client and server modules have different test libraries, being Jest for the client and Mocha for the language server. It is better to have only one, and probably Jest is the best option right now because it gives more features out of the box (like coverage report).

Before starting to work into this issue, we should discuss if we want to extract the language servers as libraries. If this is the case, it makes no sense because there will be only one test suite in the client module.

**Comment by cbjuan** [comment]
Solved in #21
