### ISSUE TITLE
OpenQASM word at the documentation

### ISSUE THREAD

**Issue by ydarias** [Qiskit/qiskit-vscode#20]
### What is the expected enhancement?

The documentation uses `Open QASM` when it is only one word like `OpenQASM`. It must be changed.

**Comment by cbjuan** [comment]
I think this has been solved in https://github.com/Qiskit/qiskit-vscode/commit/6f8953f72feddda91bc2bdd94620e6093c724cc6 Is it?

**Comment by ydarias** [comment]
Yes, I pushed it by error to the master branch from my local copy. I protected the branch to avoid the same mistake again.
