### ISSUE TITLE
IBM Q Device Status

### ISSUE THREAD

**Issue by scrowder829** [Qiskit/qiskit-vscode#33]
### Informations

- **VSCode version**: 1.27.2
- **Qiskit (Python SDK) version**: 0.5.7
- **Qiskit VSCode Extension version**: 0.3.3
- **Operating system**: MacOS 10.13.3

### What is the current behavior?
qiskit-vscode: IBM Q Device Status no longer shows IBM Q Device status ... appears to be linked to change of name of 16Q system

"/Users/scottcrowder/.vscode/extensions/qiskit.qiskit-vscode-0.3.3/resources/qiskitScripts/listRemoteBackends.py", line 85, in <module> main() File "/Users/scottcrowder/.vscode/extensions/qiskit.qiskit-vscode-0.3.3/resources/qiskitScripts/listRemoteBackends.py", line 55, in main fullInfoBack = createDeviceStatus(back) File "/Users/scottcrowder/.vscode/extensions/qiskit.qiskit-vscode-0.3.3/resources/qiskitScripts/listRemoteBackends.py", line 64, in createDeviceStatus 'name': PUBLIC_NAMES[back], KeyError: 'ibmq_16_melbourne'

### Steps to reproduce the problem
consistent behavior

### What is the expected behavior?
shows Q device status

### Suggested solutions
add ibmq_16_melbourne

**Comment by cbjuan** [comment]
Hi @scrowder829. Thanks for reporting the issue. We are aware of it, we will release a fix as soon as possible.

Kind regards

**Comment by cbjuan** [comment]
Hi @scrowder829. The new version 0.3.4 which includes the fix to this issue is now published in VSCode Marketplace https://marketplace.visualstudio.com/items?itemName=qiskit.qiskit-vscode

Thanks!
