### ISSUE TITLE
Click "X" to "Clear Notification" installs the package

### ISSUE THREAD

**Issue by muneerqu** [Qiskit/qiskit-vscode#40]
### Informations

- **VSCode version**: 1.28.1
- **Qiskit (Python SDK) version**: Qiskit 0.6.1 & Python 3.7
- **Qiskit VSCode Extension version**: 0.3.4
- **Operating system**: CentOS 7 & Win 10

### What is the current behavior?

Click on `X` to `Clear Notification (Delete)` installs the package.

### Steps to reproduce the problem

In an env where `qiskit` is not installed, open any `.py` file and you get notifications from `"Source:qiskit-vscode (Extension)`. Click `X` to `Clear Notification (Delete)` and that package gets installed.

![qiskitvscode](https://user-images.githubusercontent.com/42324856/46910524-e42b7800-cefa-11e8-881d-a501807baabe.gif)

### What is the expected behavior?

Click `X` to `Clear Notification (Delete)` only clears the notification.

**Comment by cbjuan** [comment]
Hi @muneerqu! Thanks for notifying to us this bug. We are solving it in PR #42, and it will be part of the next minor release of `qiskit-vscode`.

Happy coding!

**Comment by ydarias** [comment]
This bug is fixed in the PR #42 and will be present in the next version of the plugin.
