### ISSUE TITLE
Getting error on startup

### ISSUE THREAD

**Issue by malmaud** [Qiskit/qiskit-vscode#68]
### Informations

-   **VSCode version**: 1.31.0
-   **Qiskit [Terra / Aqua / other] version**: 0.7.2
-   **Qiskit VSCode Extension version**: 0.5.1
-   **Operating system**: OS X 10.14.2

I'm seeing the attached screenshot when I open up a blank Python buffer.
![screen shot 2019-02-08 at 4 08 55 pm](https://user-images.githubusercontent.com/987837/52506308-2a989700-2bbc-11e9-9001-af9520fd6160.png)

**Comment by cbjuan** [comment]
Hi @malmaud 

Can you paste the code you are using to test? I would like to reproduce the issue in my local machine.

Thanks

**Comment by malmaud** [comment]
No code - I just installed the extension, created a new python file, and saw the error siren above that the extension host terminated. I then clicked the 'open developer tools' button on that error popup.

**Comment by cbjuan** [comment]
That's super weird. Sorry about that, we are going to take a look at this.

**Comment by lgj2911** [comment]
Hi, the same thing happens to me, but the error appears after I install the qiskit VSC addon... And I followed all the instructions to install qiskit and the extension... 

I am attaching a screen capture
<img width="1406" alt="captura de pantalla 2019-02-20 a la s 08 57 26" src="https://user-images.githubusercontent.com/4606101/53090332-d6f84880-34ed-11e9-9e38-b211c889ca6d.png">

**Comment by cbjuan** [comment]
Hi @malmaud and @lgj2911. We are into this; it seems to be related to this issue https://github.com/Microsoft/vscode/issues/68024

We are trying to figure out [how to address it](https://github.com/Microsoft/vscode/issues/68024#issuecomment-461707138). We will inform you when we solve it.

**Comment by cbjuan** [comment]
Hi @malmaud and @lgj2911 

We are releasing the version v0.5.2. In the tests done, the extension works as expected. Please, reopen this issue if you find again the error on startup.

Thanks
